# fly.toml app configuration file generated for note-nest on 2024-01-31T22:52:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "note-nest"
primary_region = "mad"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
